#!/usr/bin/env python3
"""Base interface for topic modules."""
from __future__ import annotations
from typing import Protocol, runtime_checkable, List

@runtime_checkable
class TopicModule(Protocol):
    name: str
    def matches(self, claim: str) -> bool: ...
    def normalize_topic(self, claim: str) -> str: ...
    def suggest_probability(self, claim: str) -> float: ...
    def suggest_resolution_criteria(self, claim: str) -> str: ...
    def rationale_templates(self, claim: str, probability: float) -> list[str]: ...
    def display_tags(self, claim: str, statement_topic: str = "") -> List[str]:
        """UI pills: phase/facet first, then entities. Omit umbrella domain label."""
        ...
